import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import GlobalProvider from "@/components/Application/GlobalProvider";

const inter = Inter({ weight: ['400', '500', '600', '700', '800'], subsets: ["latin"], display: 'swap' });

export const metadata: Metadata = {
  title: "Chien Tran E-Commerce",
  description: "A complete e-commerce application with Next.js and Wix",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Ecommerce Shop</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </head>
      <body className={inter.className}>
        {/* <Navbar /> */}
        <GlobalProvider>
            {children}
        </GlobalProvider>
        
        {/* <Footer /> */}
      </body>
    </html>
  );
}
